---
- name: Install docker dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present

- name: Add docker official gpg key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker apt repository
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes

- name: Install docker
  apt:
    name: docker-ce
    state: present

- name: Install docker python module
  pip:
    name: docker
    state: present
    version: 4.0.2

- name: Docker system prune every 14 hours
  cron:
    name: 'docker-prune'
    minute: '0'
    hour: '*/12'
    job: 'docker container prune -f'

- name: Add ubuntu user to docker group
  user:
    name: ubuntu
    groups: docker
    append: yes
